name: goreleaser

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.step1.outputs.version }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.2
      - name: Get version
        id: get_version
        run: echo "::set-output name=version::$(cat VERSION)"
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_VERSION: ${{ steps.goreleaser.outputs.version}}